import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      {/* <header className='flex items-center gap-5 fixed top-0 left-0 w-full h-fit p-3 z-30 bg-slate-800'>
        <a href="/" className='p-1 rounded bg-accent text-white'>Inicio</a>
      </header> */}
      <body className={inter.className}>{children}</body>
    </html>
  )
}
